# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v2.0.0-beta

pool:
  vmImage: 'ubuntu-18.04'


variables:
  dockerId: z921190200@163.com  
  namespace: nexter
  imageName: fintech  # Replace with the name of the image you want to publish
  dockerfile: Nexter.FinTech/Nexter.Fintech.Web.Entry/Dockerfile
  registry: registry.cn-hangzhou.aliyuncs.com

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo ready to execute command
      ls
      sed -i 's/{ConnectionStr}/$(Writable)/g' Nexter.FinTech/Nexter.Fintech.Web.Entry/appsettings.json
      echo command executed
- script: |
    docker build  -f $(dockerfile) -t $(imageName) .
    docker login -u $(dockerId) --password $(AliyunDockerPwd) $(registry)
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)
  displayName: push to aliyun 