// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace FinTech.Domain
{

    // Categories
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Category
    {
        public long Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 32)
        public string Icon { get; set; } // Icon (length: 64)

        ///<summary>
        /// 1=Spending , 2= Income
        ///</summary>
        public int? Type { get; set; } // Type
    }

}
// </auto-generated>
