// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace FinTech.Domain
{

    // Member
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Member
    {
        public long Id { get; set; } // Id (Primary key)
        public long GroupId { get; set; } // GroupId

        ///<summary>
        /// 昵称
        ///</summary>
        public string NickName { get; set; } // NickName (length: 32)

        ///<summary>
        /// 微信Token
        ///</summary>
        public string AccountCode { get; set; } // AccountCode (length: 256)

        public Member()
        {
            GroupId = 0;
        }
    }

}
// </auto-generated>
