// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace FinTech.Domain
{

    // Transaction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Transaction
    {
        public long Id { get; set; } // Id (Primary key)
        public string Memo { get; set; } // Memo (length: 128)
        public long AccountId { get; set; } // AccountId

        ///<summary>
        /// 账本ID
        ///</summary>
        public long BookId { get; set; } // BookId

        ///<summary>
        /// 花销
        ///</summary>
        public decimal? Spending { get; set; } // Spending

        ///<summary>
        /// 收入
        ///</summary>
        public decimal Income { get; set; } // Income

        ///<summary>
        /// 日期
        ///</summary>
        public System.DateTime CreatedAt { get; set; } // CreatedAt
        public System.DateTime LastModifiedAt { get; set; } // LastModifiedAt

        public Transaction()
        {
            CreatedAt = System.DateTime.Now;
            LastModifiedAt = System.DateTime.Now;
        }
    }

}
// </auto-generated>
